name: Laravel

on:
  push:
    branches: [ "changements" ]
  pull_request:
    branches: [ "changements" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    env:
      DB_DATABASE: LaraDESK
      DB_USER: root
      DB_PASSWORD: root

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.prod', '.env');"
    - name: Composer update
      run: composer update --prefer-dist  --no-interaction --no-progress --no-dev --optimize-autoloader
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    #- name: Run Laravel Tests
      #run: vendor/bin/phpunit
    - name: OSKAR-phpstan
    # You may pin to the exact commit or the version.
    # uses: OskarStark/phpstan-ga@8059ab63bd7f15e5d66a3fa08a85495922139a33
      uses: OskarStark/phpstan-ga@1.4.6
      with:
        args: analyse ressource app
